openapi: '3.0.2'
info:
  title: On boarding
  description: Mon STD22075
  version: '1.3'
servers:
  - url: https://std22075.com
paths:
  /students:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/students'
        '500':
          description: Internal server error
    post:
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/students'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/students'
        '500':
          description: Internal server error

components:
  schemas:
    students:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Axel
          
